language: android

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-24.0.2
  - echo y | android update sdk -u -a -t android-24
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

android:
  components:
    # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

sudo: required

script: ./gradlew assemblePlainDebug assemblePlainRelease
